const patients=[
 {id:'BR-10482',name:'Madhumita Ghosh',age:57,phone:'•••• 1824',status:'overdue',label:'Overdue 148 days',last:'16 May 2025',next:'16 Aug 2025',risk:'HbA1c rising',events:[['16 May 2025','HbA1c · 8.9%','Up from 7.8% at the previous check'],['16 May 2025','Billing record · OPD visit','Returned for medication refill'],['12 Feb 2025','HbA1c · 7.8%','Lab result linked from AKTIV'] ],message:'নমস্কার মধুমিতা, আপনার ডায়াবেটিসের পরবর্তী পরীক্ষা বাকি আছে। Barasat clinic-এ এই সপ্তাহে একটি সময় বুক করতে ১ রিপ্লাই করুন।'},
 {id:'BR-08831',name:'Subir Dutta',age:64,phone:'•••• 4408',status:'overdue',label:'Overdue 121 days',last:'12 Jun 2025',next:'12 Sep 2025',risk:'No recent refill',events:[['12 Jun 2025','HbA1c · 9.4%','Above the clinic follow-up threshold'],['12 Jun 2025','Lipid panel · completed','LDL 142 mg/dL'],['04 Mar 2025','HbA1c · 8.7%','Lab result linked from AKTIV']],message:'Hello Subir, your diabetes follow-up is overdue. Reply 1 and we will call you to arrange a convenient time.'},
 {id:'BR-11602',name:'Nasima Khatun',age:49,phone:'•••• 9072',status:'slipping',label:'Pattern slipping',last:'18 Jan 2026',next:'18 Apr 2026',risk:'15-month gap',events:[['18 Jan 2026','HbA1c · 8.1%','Returned after a 15-month gap'],['18 Jan 2026','Record linked','Phone and Bengali name matched'],['10 Oct 2024','HbA1c · 7.2%','Last completed follow-up']],message:'নমস্কার নাসিমা, আপনার শেষ ডায়াবেটিস পরীক্ষা কিছুদিন আগে হয়েছিল। এই মাসে clinic-এ আসতে পারবেন? ১ রিপ্লাই করুন।'},
 {id:'BR-09544',name:'Arindam Sen',age:41,phone:'•••• 6619',status:'due',label:'Due in 8 days',last:'03 Jul 2026',next:'11 Oct 2026',risk:'Routine recall',events:[['03 Jul 2026','HbA1c · 6.8%','Stable at last follow-up'],['03 Jul 2026','BP · 128/82','Routine review'],['08 Apr 2026','HbA1c · 6.9%','Lab result linked from AKTIV']],message:'Hello Arindam, your next diabetes check is due soon. Reply 1 if you would like our team to call you.'},
 {id:'BR-07319',name:'Bimal Roy',age:71,phone:'•••• 2380',status:'overdue',label:'Overdue 96 days',last:'29 Jun 2025',next:'29 Sep 2025',risk:'Multiple missed recalls',events:[['29 Jun 2025','HbA1c · 10.2%','Highest recorded result'],['29 Jun 2025','Follow-up missed','No billing or lab activity since'],['15 Mar 2025','HbA1c · 9.1%','Lab result linked from AKTIV']],message:'Hello Bimal, the Barasat diabetes team would like to check in. Reply 1 and we will call you.'},
 {id:'BR-12177',name:'Rina Das',age:52,phone:'•••• 3125',status:'slipping',label:'Pattern slipping',last:'07 Dec 2025',next:'07 Mar 2026',risk:'Second missed recall',events:[['07 Dec 2025','HbA1c · 7.9%','Up from 7.1%'],['07 Dec 2025','Follow-up completed','Record linked across two IDs'],['23 Aug 2025','HbA1c · 7.1%','Lab result linked from AKTIV']],message:'নমস্কার রিনা, আপনার পরবর্তী ডায়াবেটিস পরীক্ষা বাকি আছে। এই সপ্তাহে clinic-এ আসতে পারবেন? ১ রিপ্লাই করুন。'}
];
let active='all',selected=null;
const $=s=>document.querySelector(s);const counts={overdue:patients.filter(p=>p.status==='overdue').length,slipping:patients.filter(p=>p.status==='slipping').length,due:patients.filter(p=>p.status==='due').length};
$('#attention').textContent=patients.length;$('#overdue').textContent=counts.overdue;$('#allCount').textContent=patients.length;$('#overdueCount').textContent=counts.overdue;$('#slippingCount').textContent=counts.slipping;$('#dueCount').textContent=counts.due;
function list(){const q=$('#search').value.toLowerCase();const rows=patients.filter(p=>(active==='all'||p.status===active)&&(`${p.name} ${p.phone} ${p.id}`.toLowerCase().includes(q)));$('#patientList').innerHTML=rows.map(p=>`<div class="patient ${selected===p.id?'selected':''}" data-id="${p.id}"><i class="status-dot ${p.status}"></i><div><div class="patient-name">${p.name}</div><div class="patient-meta">${p.id} · ${p.phone}</div><span class="badge ${p.status}">${p.label}</span></div><span class="patient-age">${p.age} yrs</span></div>`).join('')||'<div class="empty" style="padding:50px 20px"><p>No one matches this view.</p></div>';document.querySelectorAll('.patient').forEach(el=>el.onclick=()=>detail(patients.find(p=>p.id===el.dataset.id)));}
function detail(p){selected=p.id;list();$('#detail').innerHTML=`<div class="detail-top"><div><p class="overline">PATIENT TIMELINE</p><h2>${p.name}</h2><div class="detail-id">${p.id} · ${p.age} years · ${p.phone}</div></div><span class="status-pill ${p.status}">${p.label}</span></div><div class="detail-grid"><div><span>Last contact</span><b>${p.last}</b></div><div><span>Next recall</span><b>${p.next}</b></div><div><span>Reason to call</span><b>${p.risk}</b></div></div><p class="section-title">Linked records · one patient view</p><div class="timeline">${p.events.map(e=>`<div class="event"><time>${e[0]}</time><strong>${e[1]}</strong><p>${e[2]}</p></div>`).join('')}</div><div class="callout"><div class="callout-head"><h3>Suggested outreach</h3><label>Human review required</label></div><div class="message">${p.message}</div><div class="actions"><button class="send" onclick="sendMessage()">Send via WhatsApp</button><button class="secondary" onclick="markDone()">Mark contacted</button></div></div>`;}
function sendMessage(){toast('Message queued for human approval');}function markDone(){toast('Marked contacted · queue updated');}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');active=c.dataset.filter;list()});$('#search').oninput=list;$('#runSync').onclick=()=>toast('Nightly sync complete · 18 records linked');list();
function refreshCounts(){if(typeof patients==='undefined')return;$('#attention').textContent=patients.length;$('#overdue').textContent=patients.filter(p=>p.status==='overdue').length;$('#allCount').textContent=patients.length;$('#overdueCount').textContent=patients.filter(p=>p.status==='overdue').length;$('#slippingCount').textContent=patients.filter(p=>p.status==='slipping').length;$('#dueCount').textContent=patients.filter(p=>p.status==='due').length}
document.getElementById('filterBtn').onclick=()=>toast('Filters are set to active follow-up risk');
